version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - .data:/data/db
    networks:
      - mongodb_network
    ports:
      - 27017:27017
    restart: unless-stopped
  
  mongo-express:
    image: mongo-express
    container_name: server-mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
    volumes:
      - .data:/data/db
    depends_on:
      - mongo
    networks:
      - mongodb_network
    ports:
      - 8081:8081
    restart: unless-stopped

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      # '10-init.sql' => this makes sure that sql is executed after DB server is properly booted up.
      - ./init.sql:/docker-entrypoint-initdb.d/10-init.sql
      - .dbdata:/var/lib/postgresql

  pgadmin:
      image: dpage/pgadmin4
      restart: always
      environment: 
          PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
          PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      ports:
        - 5050:80
      depends_on: 
          - postgres 
volumes:
  mongodb-data:
    name: mongodb-data

networks:
  mongodb_network:
